In [1]:
# structured data:numpy's structured arrays

In [2]:
import numpy  as np


Imagine that we have several categories of data on a number of people (say, name, age, and weight), 


In [3]:
name = ['Alice', 'Bob', 'Cathy', 'Doug']
age = [25, 45, 37, 19]
weight = [55.0, 85.5, 68.0, 61.5]

In [5]:
x = np.zeros(4, dtype=int)

In [11]:
# Use a compound data type for structured arrays
data = np.zeros(4, dtype={'names':('name', 'age', 'weight'),
                          'formats':('U10', 'i4', 'f8')})
print(data.dtype)

[('name', '<U10'), ('age', '<i4'), ('weight', '<f8')]


In [12]:
data['name'] = name
data['age'] = age
data['weight'] = weight
print(data)

[('Alice', 25, 55. ) ('Bob', 45, 85.5) ('Cathy', 37, 68. )
 ('Doug', 19, 61.5)]


In [14]:
print(data['name'])
print(data[-1]['name'])

['Alice' 'Bob' 'Cathy' 'Doug']
Doug


In [16]:
data[data['age']<30]['name']

array(['Alice', 'Doug'], dtype='<U10')

## creating structured arrays

In [28]:
np.dtype({'names':('name', 'age', 'weight'),
          'formats':('U10', 'i4', 'f8')})
# equivalently
np.dtype({'names':('name', 'age', 'weight'),
          'formats':((np.str_,10), int, np.float32)})

dtype([('name', '<U10'), ('age', '<i8'), ('weight', '<f4')])

In [29]:
np.dtype([('name', 'S10'), ('age', 'i4'), ('weight', 'f8')])

dtype([('name', 'S10'), ('age', '<i4'), ('weight', '<f8')])

In [31]:
np.dtype('S10,i4,f8')

dtype([('f0', 'S10'), ('f1', '<i4'), ('f2', '<f8')])

## more advanced compound type

In [32]:
tp = np.dtype([('id', 'i8'), ('mat', 'f8', (3,3))])

In [36]:
x = np.zeros(1, dtype=tp)
print(x[0])
print(x['mat'])

(0, [[0., 0., 0.], [0., 0., 0.], [0., 0., 0.]])
[[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]]
