In [1]:
import numpy as np
import scipy

# 基本功能

## 与Numpy互动

In [2]:
a = np.concatenate(([3], [0]*5, np.arange(-1, 1.002, 2/9.0)))

In [8]:
a = np.r_[3, [0]*5, -1:1:10j]
a

array([ 3.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        , -1.        , -0.77777778, -0.55555556, -0.33333333,
       -0.11111111,  0.11111111,  0.33333333,  0.55555556,  0.77777778,
        1.        ])

## 多项式

In [27]:
# 导入多项式库
from numpy import poly1d 
# 创建多项式3X**2 + 4 X**1 + 5
p = poly1d([3,4,5])
print(p)

print('----')
# 多项式的平方
print(p*p)  

# p.integ()
# 求导
print(p.deriv())  
# 求值，分别求列表里面的值
print(p([1,2,3]))

   2
3 x + 4 x + 5
----
   4      3      2
9 x + 24 x + 46 x + 40 x + 25
 
6 x + 4
[12 25 44]


## 向量化函数

In [28]:
def addsubtract(a, b):
    if a > b:
        return a - b
    else:
        return a + b
    

In [31]:
# 向量化函数，这样的函数可以向ndarray一样操作
vec_addsubtract = np.vectorize(addsubtract) 
vec_addsubtract([1,2,3,4,5],[2,3,4,5,1])

array([3, 5, 7, 9, 4])