In [2]:
import numpy as np

np.__version__

'1.16.4'

## python 列表不只是列表
### python列表与c语言相比
+ c语言之存放一种数据
+ python列表保存数据之外，还携带了对象头（pyobject_HEAD），序列，引用

### numpy array之存储了数据，对象头，维度，提高数据访问速度
**numpy arrary 要求数据类型要一致**

### 从python列表创建数组

In [3]:
# 整型数组
np.array([1,2,3,5,4])

array([1, 2, 3, 5, 4])

**如果数组的数据类型不同，numpy会自动向上转换(如果可以话)，否则报错**

In [4]:
arr = np.array([3.13,23,5,4,5])
print(arr)
print(arr.dtype)

[ 3.13 23.    5.    4.    5.  ]
float64


#### 指定数据类型

In [7]:
arr = np.array([1,2,3,4,2,4,3], dtype='float32')
print(arr)
print(arr.dtype)

[1. 2. 3. 4. 2. 4. 3.]
float32


#### 多维数组创建

In [10]:
arr = np.array([range(i, i+3) for i in [2,4,6]])
print(arr)
print(arr.shape)

[[2 3 4]
 [4 5 6]
 [6 7 8]]
(3, 3)


#### 从头开始创建数组

In [11]:
# 创建一个长度为10的数组，数组的值都是0
arr = np.zeros(10, dtype=int)
print(arr)

[0 0 0 0 0 0 0 0 0 0]


In [17]:
# np.ones((shape), dtype)
# 创建一个3x5的浮点型数组，数值都是1
arr = np.ones((3,5), dtype=float)
print(arr)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [18]:
# 创建一个3x5的整型数组，数组的值都是3.1
arr = np.full((3,5), 3.1)
print(arr)

[[3.1 3.1 3.1 3.1 3.1]
 [3.1 3.1 3.1 3.1 3.1]
 [3.1 3.1 3.1 3.1 3.1]]


In [20]:
# np.range(start, stop, step)
arr = np.arange(0, 20, 2)  
print(arr)
print(arr.shape)

[ 0  2  4  6  8 10 12 14 16 18]
(10,)


In [22]:
# np.linspace(start, stop, num)
# 创建一个5个元素的数组，将5个数均匀地分配到0-1
arr = np.linspace(0,1,5)
print(arr)

[0.   0.25 0.5  0.75 1.  ]


In [25]:
arr = np.linspace(0,5, 11)
print(arr)
print(arr.shape)

[0.  0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5 5. ]
(11,)


In [26]:
# 创建一个3x3的、在0-1分布的随机数组成的数组
np.random.random((3, 3))

array([[0.98726921, 0.90911432, 0.82352156],
       [0.17690527, 0.53896543, 0.18262422],
       [0.07211053, 0.70647022, 0.93766855]])

In [28]:
# np.random.normal(mean, var, (shape)) 
# 创建一个正态分布，均值mean，方差ar，维度shape
# 创建一个3x3的均值为0，方差为1的正态分布随即数组
arr = np.random.normal(0,1,(3, 3))
print(arr)

arr2 = np.random.normal(5, 10, (3, 3))
print(arr2)

[[-0.61622142 -0.43910492  1.94543509]
 [-1.91292688 -0.46696946 -0.81436161]
 [ 0.30100004 -0.29203155  0.55897945]]
[[-0.27195684 -1.14913495 -1.21282477]
 [ 6.67506066 30.16302688  1.51925576]
 [-8.0760176  13.52430205 14.14992214]]


In [29]:
# 创建一个3✖3的【0， 10】区间的随即证书类型数据
arr = np.random.randint(0, 10, (3, 3))
print(arr)

[[9 3 8]
 [2 7 6]
 [2 7 4]]


In [31]:
# 创建3✖3的单位矩阵
arr = np.eye(3)
print(arr)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [33]:
# 创建一个3✖3的空数组，数组里面的数据为垃圾数据
arr = np.empty((3,3))
print(arr)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


### numpy标准数据类型

## numpy数组基础

### numpy数组的属性


In [43]:
import numpy as np
np.random.seed(0)

# np.random.randint(start, stop, size=(dim, shape))
x1 = np.random.randint(10, size=6) # 一维数组
x2 = np.random.randint(10, size=(3,4)) # 二维
x3 = np.random.randint(10, size=(3, 4, 5))  # 三维
# print(x1, end="\n")
# print(x2, end="\n")
print(x3)

[[[8 1 5 9 8]
  [9 4 3 0 3]
  [5 0 2 3 8]
  [1 3 3 3 7]]

 [[0 1 9 9 0]
  [4 7 3 2 7]
  [2 0 0 4 5]
  [5 6 8 4 1]]

 [[4 9 8 1 1]
  [7 9 9 3 6]
  [7 2 0 3 5]
  [9 4 4 6 4]]

 [[4 3 4 4 8]
  [4 3 7 5 5]
  [0 1 5 9 3]
  [0 5 0 1 2]]]


#### 属性
+ x.ndim(数组维度)
+ x.shape(数组维度的大小)
+ size(数组总大小)
+ dtype(类型)

In [47]:
print("x3 ndim: ", x3.ndim)
print("x3 shape: ", x3.shape)
print("x3 size: ", x3.size)
print("x3 dtype: ", x3.dtype)

x3 ndim:  3
x3 shape:  (4, 4, 5)
x3 size:  80
x3 dtype:  int64


### 数组索引：获取单个元素

#### 一维：和python列表类似

#### 多维：用逗号分割的索引元组获取元素

In [55]:
print(x2)
print(x2[0, 0])
print(x2[0, -1])

# 修改元素值
x2[0,-1] = 100000
print(x2)

[[5 3 1 8]
 [0 4 9 6]
 [5 7 8 8]
 [9 2 8 6]]
5
8
[[     5      3      1 100000]
 [     0      4      9      6]
 [     5      7      8      8]
 [     9      2      8      6]]


In [57]:
# 若插入的类型不一样，数据会被修改
x1 = np.arange(0, 10)
x1[0] = 3.33333333333
print(x1)

[3 1 2 3 4 5 6 7 8 9]


### 数组切片：获取子数组
x[start: stop: step, start:stop:step,....]

#### 一维子数组

In [59]:
x = np.arange(10)
print(x[ :5])  # 前5个元素

print(x[6:])  # 后5个元素

print(x[1:3])  # 中间元素

print(x[::2])  # 每隔一个元素



[0 1 2 3 4]
[6 7 8 9]
[1 2]
[0 2 4 6 8]



#### 多维子数组
x[start: stop: step, start:stop:step,....]  
x[行， 列]

In [62]:
x2 = np.random.randint(10, size=(3,4))
x2

array([[5, 3, 4, 5],
       [3, 3, 7, 9],
       [9, 9, 7, 3]])

In [64]:
x3 = np.random.randint(10, size=(4,4,5))
x3

array([[[2, 3, 9, 7, 7],
        [5, 1, 2, 2, 8],
        [1, 5, 8, 4, 0],
        [2, 5, 5, 0, 8]],

       [[1, 1, 0, 3, 8],
        [8, 4, 4, 0, 9],
        [3, 7, 3, 2, 1],
        [1, 2, 1, 4, 2]],

       [[5, 5, 5, 2, 5],
        [7, 7, 6, 1, 6],
        [7, 2, 3, 1, 9],
        [5, 9, 9, 2, 0]],

       [[9, 1, 9, 0, 6],
        [0, 4, 8, 4, 3],
        [3, 8, 8, 7, 0],
        [3, 8, 7, 7, 1]]])

In [67]:
x3[:3, :2, :3]
x3[::-1, ::-1, ::-1]

array([[[1, 7, 7, 8, 3],
        [0, 7, 8, 8, 3],
        [3, 4, 8, 4, 0],
        [6, 0, 9, 1, 9]],

       [[0, 2, 9, 9, 5],
        [9, 1, 3, 2, 7],
        [6, 1, 6, 7, 7],
        [5, 2, 5, 5, 5]],

       [[2, 4, 1, 2, 1],
        [1, 2, 3, 7, 3],
        [9, 0, 4, 4, 8],
        [8, 3, 0, 1, 1]],

       [[8, 0, 5, 5, 2],
        [0, 4, 8, 5, 1],
        [8, 2, 2, 1, 5],
        [7, 7, 9, 3, 2]]])

#### 获取数组的某一行，某一列

In [69]:
x2

array([[5, 3, 4, 5],
       [3, 3, 7, 9],
       [9, 9, 7, 3]])

In [71]:
print(x2[:, 0])  # 第一列

print(x2[1, :])  # 第二行 
print(x2[1])  # 作用同上

[5 3 9]
[3 3 7 9]
[3 3 7 9]


#### 修改数组原来的数组也会改变


In [72]:
x2_sub = x2[:2, :2]
print(x2_sub)

[[5 3]
 [3 3]]


In [74]:
x2_sub[0, 0] = 999
print(x2_sub)

[[999   3]
 [  3   3]]


In [77]:
#### 创建副本
x2_sub_copy = x2[:2, :2].copy()
x2_sub_copy[0,0] = 3
print(x2_sub_copy)

print(x2_sub)

[[3 3]
 [3 3]]
[[999   3]
 [  3   3]]


#### 数组变形
+ arr.reshape((shape))  # size == shape
  
  the size of the initial array must match the size of the reshaped array

In [86]:
re_arr = np.arange(1, 10).reshape((3,3))
print(re_arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [88]:
re_arr = np.arange(60).reshape(3,4,5)
print(re_arr)

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]
  [30 31 32 33 34]
  [35 36 37 38 39]]

 [[40 41 42 43 44]
  [45 46 47 48 49]
  [50 51 52 53 54]
  [55 56 57 58 59]]]


+ 通过切片实现

In [91]:
x = np.array([1,2,3])
x2 = x[np.newaxis, :]  # 相当于 x.reshape((1,3))
print(x2)

x3 = x[:, np.newaxis]  # 相当于 x.reshape((3, 1))
print(x3)

[[1 2 3]]
[[1]
 [2]
 [3]]


In [97]:
x = np.arange(25)
x.reshape(5,1,5)

array([[[ 0,  1,  2,  3,  4]],

       [[ 5,  6,  7,  8,  9]],

       [[10, 11, 12, 13, 14]],

       [[15, 16, 17, 18, 19]],

       [[20, 21, 22, 23, 24]]])

#### 数组的拼接和分裂

+ 拼接
    + np.concatenate
    + np.vstack
    + np.hstack

##### np.concatenate([])
+ 一维数组

In [100]:
x = np.array([1,2,3])
y = np.array([3,2,3])
np.concatenate([x, y])

array([1, 2, 3, 3, 2, 3])

In [102]:
z = [99,9,9,9,0]
np.concatenate([x, y, z])

array([ 1,  2,  3,  3,  2,  3, 99,  9,  9,  9,  0])

+ 多维数组

In [120]:
grid = np.arange(1, 7).reshape((2,3))
grid2 = np.concatenate([grid, grid])  # 沿第一个轴拼接，行拼接
print(grid2)

grid3 = np.concatenate([grid, grid],axis=1)  # 沿第二个轴拼接，列拼接
print(grid3)

[[1 2 3]
 [4 5 6]
 [1 2 3]
 [4 5 6]]
[[1 2 3 1 2 3]
 [4 5 6 4 5 6]]


In [123]:
grid = np.arange(18).reshape((2,3,3))
print(grid)
print("-"*50)
grid2 = np.concatenate([grid, grid], axis=0)
print(grid2)

print("-"*50)
grid2 = np.concatenate([grid, grid], axis=1)
print(grid2)

print("-"*50)
grid2 = np.concatenate([grid, grid], axis=2)
print(grid2)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]]
--------------------------------------------------
[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]]
--------------------------------------------------
[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]
  [ 9 10 11]
  [12 13 14]
  [15 16 17]]]
--------------------------------------------------
[[[ 0  1  2  0  1  2]
  [ 3  4  5  3  4  5]
  [ 6  7  8  6  7  8]]

 [[ 9 10 11  9 10 11]
  [12 13 14 12 13 14]
  [15 16 17 15 16 17]]]


+ 垂直栈，水平栈

In [126]:
x1 = np.array([1,2,3])
x2 = np.array([[7,8,9],
               [4,5,6]])
print(np.vstack([x1, x2]))

[[1 2 3]
 [7 8 9]
 [4 5 6]]


In [130]:
x3 = np.array([[99, 100], [99, 100]])
print(np.hstack([x2, x3]))

[[  7   8   9  99 100]
 [  4   5   6  99 100]]


##### 数组的分裂
+ np.split(array, [分割点])
+ np.hsplit
+ np.vsplit

In [133]:
x = [1, 2, 3, 99, 99,3, 2, 1]
x1, x2, x3 = np.split(x, [3,5])
print(x1, x2, x3)

[1 2 3] [99 99] [3 2 1]
