# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow and in the numpy documentation. The goal of this collection is to offer a quick reference for both old and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel free to open an issue at <https://github.com/rougier/numpy-100>

#### 1. Import the numpy package under the name `np` (★☆☆)

In [1]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [2]:
np.__version__

'1.16.2'

#### 3. Create a null vector of size 10 (★☆☆)

In [6]:
arr = np.full(10, np.nan)

#### 4.  How to find the memory size of any array (★☆☆)

In [24]:
print(arr.size, arr.itemsize)
arr

6 4


array([1, 2, 0, 0, 4, 0])

#### 5.  How to get the documentation of the numpy add function from the command line? (★☆☆)

In [26]:
%run `python -c "import numpy;numpy.info(numpy.add)"

ERROR:root:File `'`python.py'` not found.


#### 6.  Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [28]:
arr = np.full(10, 0)
arr[4] = 1
arr

array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0])

#### 7.  Create a vector with values ranging from 10 to 49 (★☆☆)

In [13]:
arr = np.arange(10, 50)

#### 8.  Reverse a vector (first element becomes last) (★☆☆)

In [14]:
arr[::-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

#### 9.  Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [17]:
np.arange(0, 9).reshape((3,3))

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 10. Find indices of non-zero elements from \[1,2,0,0,4,0\] (★☆☆)

In [31]:
np.nonzero([1,2,0,0,4,0])

(array([0, 1, 4], dtype=int64),)

#### 11. Create a 3x3 identity matrix (★☆☆)

In [32]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 12. Create a 3x3x3 array with random values (★☆☆)

In [33]:
np.random.random((3,3,3))

array([[[0.89325637, 0.96849614, 0.94075575],
        [0.2454937 , 0.37578262, 0.45965938],
        [0.9593835 , 0.71917103, 0.37726353]],

       [[0.13670071, 0.27179487, 0.09150434],
        [0.71116919, 0.62503141, 0.63820854],
        [0.31385858, 0.82726277, 0.56365532]],

       [[0.0821235 , 0.15263316, 0.79911482],
        [0.48370143, 0.77487273, 0.48736506],
        [0.61442044, 0.91619095, 0.166686  ]]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [37]:
arr = np.random.random((10,10))

print(arr.max())
print(arr.min())


0.9852843266477211
0.008508932170035233


#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [39]:
arr = np.random.random(30)
print(arr.mean())

0.5578644574237361


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [42]:
arr = np.ones((10,10))
arr[1:-1, 1:-1]=0
arr

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [46]:
arr = np.zeros((10,10))
arr = np.pad(arr, pad_width=1, mode='constant', constant_values=1)
arr

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

#### 17. What is the result of the following expression? (★☆☆)

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [54]:
# nan
# False
# False
# nan
# True
# False
print(0*np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan -np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * .1)

nan
False
False
nan
True
False



#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [58]:
arr = np.diag(1+np.arange(4), k=1)
arr

array([[0, 1, 0, 0, 0],
       [0, 0, 2, 0, 0],
       [0, 0, 0, 3, 0],
       [0, 0, 0, 0, 4],
       [0, 0, 0, 0, 0]])

#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [60]:
arr = np.zeros((8,8))
arr[1::2, ::2] = 1
arr[::2, 1::2] = 1
arr

array([[0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.]])

#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [71]:
arr = np.arange(1, 6*7*8+1).reshape((6,7,8))
arr[1, 5, 3]
print(np.unravel_index(99, (6,7,8)))

(1, 5, 3)


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [87]:
arr = np.array([[0,1],[1,0]])
np.tile(arr, (4,4))


array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

#### 22. Normalize a 5x5 random matrix (★☆☆)

In [90]:
arr = np.random.random((5,5))
arr = (arr - arr.mean()) / arr.std()
arr

array([[ 1.21411418, -0.37935707, -1.16355408,  0.9552449 , -0.89991376],
       [ 1.41011259, -1.09069223,  1.35203843, -0.74325495, -0.50032668],
       [ 1.07762038, -0.32011132, -0.82151014,  1.14453419,  0.83794832],
       [ 1.05273314, -0.87024351, -0.28485968,  0.25006553, -1.4113226 ],
       [-1.41257467,  1.67949406, -1.14781035,  0.48809386, -0.41646853]])

#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [92]:
color = np.dtype([("r", np.ubyte, 1),
                  ("g", np.ubyte, 1),
                  ("b", np.ubyte, 1),
                  ("a", np.ubyte, 1)])
color

dtype([('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')])

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [95]:
arr1 = np.random.random((5,3))
arr2 = np.random.random((3,2))
arr = np.dot(arr1, arr2)
arr

array([[1.44528143, 1.25084363],
       [1.03504946, 0.64397978],
       [1.3714606 , 0.9704698 ],
       [0.3320686 , 0.20152872],
       [1.64748225, 1.10359584]])

#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [102]:
arr = np.random.randint(0,10, 25)
arr[(arr>=3) & (arr<=8)] *= -1
arr

array([-4, -8,  2,  9, -4, -3, -8, -8, -3, -6, -5, -6, -6,  9, -5,  0,  0,
       -6,  1,  9,  2, -6, -4, -8, -7])

#### 26. What is the output of the following script? (★☆☆)

```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [113]:
print(sum(range(5), -1))
print(np.sum(range(5), -1))
# np.sum([0,1,2,3,4], -1)
list(range(5))

9
10


[0, 1, 2, 3, 4]

#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)

```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [140]:
Z = np.array([1,2,3])
# Z**Z
print(Z**Z)
print(Z<-Z)
1j *Z


[ 1  4 27]
[False False False]


array([0.+1.j, 0.+2.j, 0.+3.j])

#### 28. What are the result of the following expressions?

```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [146]:
np.array([np.nan]).astype(int).astype(float)

array([-2.14748365e+09])

#### 29. How to round away from zero a float array ? (★☆☆)

In [151]:
arr = np.random.uniform(-10, 10, 10)
# np.copysign()


#### 30. How to find common values between two arrays? (★☆☆)

In [170]:
arr1 = np.arange(1, 10)
arr2 = np.arange(5,14)
np.intersect1d(arr1, arr2)


array([5, 6, 7, 8, 9])

#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [178]:
# Suicide mode on
defaults = np.seterr(all='ignore')
np.ones(1) /0

# Back to sanity
_ = np.seterr(**defaults)

# equivalently next
with np.errstate(divide='ignore'):
    Z = np.ones(1) / 0

#### 32. Is the following expressions true? (★☆☆)

```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [175]:
np.emath.sqrt(-1)  == np.sqrt(-1)

False

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [183]:
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
print('yesterday is :',yesterday)
today = np.datetime64('today', 'D')
print('today is : ', today)
tomorrow = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print('tomorrow is :', tomorrow)

yesterday is : 2019-10-27
today is :  2019-10-28
tomorrow is : 2019-10-29


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [184]:
np.arange('2016-07', '20116-08', dtype='datetime64[D]')

array([ '2016-07-01',  '2016-07-02',  '2016-07-03', ..., '20116-07-29',
       '20116-07-30', '20116-07-31'], dtype='datetime64[D]')

#### 35. How to compute ((A+B)\*(-A/2)) in place (without copy)? (★★☆)

In [90]:
A = np.arange(0,3)
B = np.ones(3)*2
C = np.ones(3)*3
# np.add(A,B,out=B)
# np.divide(A,2,out=A)
# np.add(A, B, out=B)


#### 36. Extract the integer part of a random array using 5 different methods (★★☆)

#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [93]:
arr = np.zeros((5,5))
arr +=  np.arange(0,5)
arr

array([[0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.]])

#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [97]:
generator = (i for i in range(11))
np.fromiter(generator, dtype=np.int8)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10], dtype=int8)

#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [99]:
np.linspace(0 ,1, 11, endpoint=False)[1:]

array([0.09090909, 0.18181818, 0.27272727, 0.36363636, 0.45454545,
       0.54545455, 0.63636364, 0.72727273, 0.81818182, 0.90909091])

#### 40. Create a random vector of size 10 and sort it (★★☆)

In [107]:
arr = np.random.randint(1, 100, size=10)
arr.sort()
print(arr)

[ 4  4 33 37 52 58 65 70 81 90]


In [110]:
arr = np.random.randint(1,100, 100)
for i in range(arr.size):
    for j in range(i, arr.size):
        if arr[i]< arr[j]:
            arr[i], arr[j] = arr[j], arr[i]
arr

array([99, 99, 99, 98, 97, 96, 93, 92, 92, 92, 91, 91, 90, 89, 87, 86, 85,
       84, 84, 82, 82, 82, 82, 80, 76, 75, 75, 73, 72, 72, 72, 71, 68, 67,
       67, 67, 67, 66, 64, 63, 62, 61, 59, 56, 55, 55, 53, 53, 52, 52, 52,
       52, 51, 51, 51, 49, 48, 44, 43, 43, 42, 41, 38, 37, 37, 36, 36, 35,
       35, 35, 34, 33, 30, 28, 27, 26, 25, 24, 22, 22, 21, 21, 20, 18, 16,
       16, 16, 16, 14, 13, 13, 11, 11, 10,  9,  9,  9,  6,  5,  4])

#### 41. How to sum a small array faster than np.sum? (★★☆)

In [121]:
arr  = np.random.randint(1, 101, 100000000)
%time arr.sum()
%time np.add.reduce(arr)

Wall time: 101 ms
Wall time: 95.7 ms


754866520

#### 42. Consider two random array A and B, check if they are equal (★★☆)

In [133]:
A = np.array([1,2,3,4], dtype=np.float64)
B = np.array([1,2,3,4.00001])
# 在误差允许的范围内，判断是否相等
print(np.allclose(A,B))
# 完全相等，不允许有误差
print(np.array_equal(A,B))


True
False


#### 43. Make an array immutable (read-only) (★★☆)

In [140]:
arr =  np.array([1,2,3])
arr.flags.writeable = False
# arr[0] =1

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [154]:
arr = np.random.randint(1,8, 10)
arr2 = arr.copy()
print(arr)
print(np.where(arr == arr.max(), 0, arr))
arr2[arr2.max()] = 0
print(arr2)

[1 7 3 4 4 6 4 6 6 3]
[1 0 3 4 4 6 4 6 6 3]
[1 7 3 4 4 6 4 0 6 3]


#### 46. Create a structured array with `x` and `y` coordinates covering the \[0,1\]x\[0,1\] area (★★☆)

In [159]:
Z = np.zeros((5,5), dtype=[('x',float),('y',float)])
Z['x'], Z['y'] = np.meshgrid(np.linspace(0,1,5),
                             np.linspace(0,1,5))
print(Z.shape)

(5, 5)


In [165]:
import itertools
g = itertools.product(np.linspace(0, 1, 5), np.linspace(0, 1, 5))
np.fromiter(g, dtype=float)

ValueError: setting an array element with a sequence.

####  47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj))

#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

#### 49. How to print all the values of an array? (★★☆)

#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

#### 54. How to read the following file? (★★☆)

```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

#### 56. Generate a generic 2D Gaussian-like array (★★☆)

#### 57. How to randomly place p elements in a 2D array? (★★☆)

#### 58. Subtract the mean of each row of a matrix (★★☆)

#### 59. How to sort an array by the nth column? (★★☆)

#### 60. How to tell if a given 2D array has null columns? (★★☆)

#### 61. Find the nearest value from a given value in an array (★★☆)

#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

#### 63. Create an array class that has a name attribute (★★☆)

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★★)

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

#### 69. How to get the diagonal of a dot product? (★★★)

#### 70. Consider the vector \[1, 2, 3, 4, 5\], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

#### 72. How to swap two rows of an array? (★★★)

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

#### 74. Given an array C that is a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

#### 75. How to compute averages using a sliding window over an array? (★★★)

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z\[0\],Z\[1\],Z\[2\]) and each subsequent row is  shifted by 1 (last row should be (Z\[-3\],Z\[-2\],Z\[-1\]) (★★★)

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i  (P0\[i\],P1\[i\])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P\[j\]) to each line i (P0\[i\],P1\[i\])? (★★★)

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

#### 81. Consider an array Z = \[1,2,3,4,5,6,7,8,9,10,11,12,13,14\], how to generate an array R = \[\[1,2,3,4\], \[2,3,4,5\], \[3,4,5,6\], ..., \[11,12,13,14\]\]? (★★★)

#### 82. Compute a matrix rank (★★★)

#### 83. How to find the most frequent value in an array?

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

#### 85. Create a 2D array subclass such that Z\[i,j\] == Z\[j,i\] (★★★)

#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

#### 91. How to create a record array from a regular array? (★★★)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. \[2,2,3\]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)

**如何根据第3列对一个多维矩阵进行排序**

In [2]:
arr = np.random.randint(1, 101, size=(7,8))
arr

array([[ 80,  90,  24,  51,  82,  41,  86,  95],
       [ 88,  75,  27,  51,  38,  14,  81,  56],
       [ 44,  87, 100,  86,  66,   9,  97,  24],
       [ 70,  34,  58,  26,  35,  53,  90,  43],
       [ 84,  44,  73,  73,  75,  40,  20,  48],
       [ 64,  62,  54,  31,  61,  87,  19,  42],
       [ 45,  14,   9,  27,  17,  94,  87,  96]])

In [11]:
index = np.argsort(arr[:, 2])
arr[index]

array([[ 45,  14,   9,  27,  17,  94,  87,  96],
       [ 80,  90,  24,  51,  82,  41,  86,  95],
       [ 88,  75,  27,  51,  38,  14,  81,  56],
       [ 64,  62,  54,  31,  61,  87,  19,  42],
       [ 70,  34,  58,  26,  35,  53,  90,  43],
       [ 84,  44,  73,  73,  75,  40,  20,  48],
       [ 44,  87, 100,  86,  66,   9,  97,  24]])

**给定一个4维向量，如何得到最后两维度的和**

In [17]:
arr = np.random.randint(4,100,(4,5,6,7))

In [20]:
arr.sum(axis=-1).sum(-1).shape

(4, 5)

In [21]:
arr.sum(axis=(-1,-2))

array([[2195, 2081, 2051, 2232, 2086],
       [2282, 2316, 2077, 1734, 2144],
       [2319, 2144, 2262, 2120, 1979],
       [2298, 2272, 2286, 2166, 2067]])

**给定数组[1，2，3，4，5], 如何得到这个数每个元素直接插入3个0后的数组**

In [56]:
arr = np.arange(1, 6)
arr2 = np.zeros((len(arr)-1)*3 + len(arr))
arr2[::4] = arr
arr2

array([1., 0., 0., 0., 2., 0., 0., 0., 3., 0., 0., 0., 4., 0., 0., 0., 5.])

**正则化（归一化）一个二维矩阵**  
正则：a = (a - min)/ (max - min)

In [59]:
arr = np.random.randint(1, 101, (4,5))
arr

array([[ 13,  68,  79,  17,  66],
       [ 35,  92,  78,  44,  68],
       [ 81,   4,  93,  93, 100],
       [ 41,  68,  41,  81,  48]])

In [60]:
v_min = np.min(arr, axis=0)
v_max = np.max(arr, axis=0)
print(v_min, ':min<--->max:', v_max)

[13  4 41 17 48] :min<--->max: [ 81  92  93  93 100]


In [62]:
(arr - v_min) / (v_max - v_min)

array([[0.        , 0.72727273, 0.73076923, 0.        , 0.34615385],
       [0.32352941, 1.        , 0.71153846, 0.35526316, 0.38461538],
       [1.        , 0.        , 1.        , 1.        , 1.        ],
       [0.41176471, 0.72727273, 0.        , 0.84210526, 0.        ]])